### ISSUE TITLE
Run R code in parallel with feature and AzureContainers

### ISSUE THREAD

**Issue by MislavSag** [Azure/AzureContainers#19]
My goal is to run R code in parallel using future package and Azure kubernets cluster.

Here is an example how to do that with AWS and GCE:
https://github.com/paciorek/future-kubernetes

I am trying to do the same with `AzureContainers` but not sure how to do that.

I have followed the code from the readme:
```

az <- AzureRMR::get_azure_login()
resgroup <- az$
    get_subscription("<subscription_id>")$
    create_resource_group("myresgroup", location="europewest")

# create container registry
acr <- resgroup$create_acr("myacr", location="europewest")

# create Docker image from a predefined Dockerfile
call_docker("build -t newcontainer .")

# get registry endpoint, upload image
reg <- acr$get_docker_registry()
reg$push("newcontainer")


# create Kubernetes cluster with 2 nodes
aks <- resgroup$create_aks("myakscluster",
    location="australiaeast",
    agent_pools=agent_pool("pool1", 2))

# give the cluster pull access to the registry
acr$add_role_assignment(aks, "Acrpull")

# get cluster endpoint, deploy from ACR to AKS with predefined yaml definition file
clus <- aks$get_cluster()
clus$create("model1.yaml")
clus$get("service")
```
I have used docker file from the repo above.

After I have created the custer, I don't understand how I can communicate with cluster from R studio.

I want to run this test code:
```
library(future)
plan(cluster, manual = TRUE, quiet = TRUE)

library(future.apply)
output <- future_lapply(1:40, function(i) mean(rnorm(1e7)), future.seed = TRUE)

library(future.apply)
future_sapply(seq_len(nbrOfWorkers()), function(i) Sys.info()[["nodename"]])
```

**Comment by MislavSag** [comment]
Could you please answer do you plan to check this question? I am in " zeitnot" and I am planning to move to aws or GCE if you don't have time to help. Those examples I posted have solutions for gce and aws.

😐

**Comment by hongooi73** [comment]
Hi,

First, I should mention that I'm no longer with Microsoft. While I'm still maintaining these packages, and I'm also still something of an MS fanboi, whether you move to AWS/GCE means not a whit to me 🙂

That said: technically you shouldn't need AzureContainers for this. The commands to create the Kubernetes cluster can be run via the `az` CLI; see the [reference](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest) for more details. There is also a [quickstart page](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough?toc=%2fcli%2fazure%2ftoc.json) to create a cluster.

Similarly, you should be able to run kubectl and helm to manage your AKS cluster just like with GKS and EKS. AzureContainers provides convenience functions to do this from R, but again, they're not strictly necessary. [Here](https://amalgjose.com/2021/05/08/how-to-configure-kubectl-for-an-azure-aks-cluster/) is a page describing how to get kubectl to talk to your cluster: basically, you run [`az aks get-credentials`](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).

Once you've setup Rstudio (which seems to be what the helm chart does), you can connect to it by browsing to `localhost:8787` as described in your link. The cluster itself is the same as with GKS/EKS, it's just that the underlying resources are being managed by Azure instead of Google or Amazon.

**Comment by MislavSag** [comment]
Thanks a lot for help.

Since you are familiar with Azure services, what would you recommend to  parallel jobs (say 16 cores) with moderate data size (say 1 mil rows and 100 columns).
I have used Batch service before, but they plan to stpo its support for R in the future. I checked Azure ML, but it seems to complicated to just run some R code in parallel.
Sorry for additional question.

**Comment by hongooi73** [comment]
You should be able to follow the steps in your original link. Like I said, the Kubernetes cluster itself works the same way regardless of whether it's deployed via AKS, EKS or GKS.

The doAzureParallel package is no longer supported, but AFAIK it should still work. If there's sufficient demand I may create a replacement.

**Comment by MislavSag** [comment]
I will with GCE first.  But Batch was much simpler. 

I succesfuuly ran the code using `az ml` , but  I am not sure this is the right approach if I just need to run somee simple code in parallel.

Thanks fro all help.
